name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalıştır
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub repository'sini kontrol eder
      - uses: actions/checkout@v3

      # Yılan animasyonunu oluşturur
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: MuhammetAkkan

      # Git durumu kontrol edilir
      - run: git status

      # Değişiklikleri push eder
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # GitHub Pages'e çıktı gönderilir
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debugging'i etkinleştir
      - name: Enable Debugging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
